name: Packer_Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_check:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Miemiemie!23
          MYSQL_DATABASE: webapp
          MYSQL_USER: beluga
          MYSQL_PASSWORD: Miemiemie!23
        ports:
          - 3306:3306
        #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check Packer Format
        run: |
          packer fmt -check packer/ami.pkr.hcl
          STATUS=$?
          if [ $STATUS -ne 0 ]; then
          echo "Packer template is not correctly formatted. Please run 'packer fmt' to format it."
          exit 1
          fi



      # Create the users.csv file
      - name: Create users.csv
        run: |
          sudo sh -c 'cat << EOF > /opt/users.csv
          first_name,last_name,email,password
          john,doe,john.doe@example.com,abc123
          jane,doe,jane.doe@example.com,xyz456
          EOF'

      - name: Build with Maven
        run: mvn -e clean install

      - name: Validate Packer Template
        run: |
          cd packer
          packer init ami.pkr.hcl
          packer validate ami.pkr.hcl
          cd ..


